### ISSUE TITLE
메인 페이지 컴포넌트 개발

### ISSUE THREAD

**Issue by LeagueLugas** [woowa-techcamp-2021/deal-20#2]
## 개요
메인 페이지 컴포넌트 개발

## 브랜치명
feature/main-page-component

## 단계별 진행상황
- [x] 메인 해더 컴포넌트
- [x] 개별 상품 컴포넌트
- [x] FAB 컴포넌트

**Comment by sanginchun** [comment]
첫 컴포넌트 개발이니까 페어로 진행해보는 것으로 결정

**Comment by sanginchun** [comment]
공통 스타일 적용 파일 수정, css 중복 문제, svg 사용 방식 등 협의 필요한 부분이 생겨서 PR 보류

**Comment by sanginchun** [comment]
- 소요시간: 4.5h
- 위 코멘트 내용 같은 문제들이 생겨서 속도가 잘 나지 않음. 문제를 잘 해결하고 구조를 잡아놓으면 생산성이 좋아질 듯.. (아마도)
