### ISSUE TITLE
SVG 아이콘 사용 방식 변경

### ISSUE THREAD

**Issue by sanginchun** [woowa-techcamp-2021/deal-20#41]
## 브랜치
feature/icons

## 설명
컴포넌트를 만들다보니 현재의 아이콘 사용 방식(width, height, fill, stroke을 인자로 넘기는)으로는 표현할 수 없는 아이콘이 있는 것을 확인했습니다. 우리가 디자인 컴포넌트 피그마에서 아이콘을 export하여 저장한 svg, path와 stroke-width가 다르거나, 아예 width, height, viewport, path가 다른 아이콘들도 있어서 사용 방식을 수정해야 할 것 같습니다.

## 예시
![스크린샷 2021-07-17 오전 1 07 39](https://user-images.githubusercontent.com/31500012/125977125-517753d0-240c-4a84-92c3-0d8acb2eec19.png)
![스크린샷 2021-07-17 오전 1 08 06](https://user-images.githubusercontent.com/31500012/125977137-9fa3b38a-42fa-4569-b919-bdb6df98b5a7.png)
세 개의 하트가 미묘하게 (크기뿐만 아니라 stroke-width, 모양 자체가) 다릅니다... ㅎ

## 해결 방안
1. 우선 각자 컴포넌트를 만들면서 필요한 아이콘 svg 값(색깔, 모양, 크기가 정해진)을 icons 폴더에 추가해서 사용한다. 이렇게 하면 인자로 뭐 넘기고 할 필요도 없어짐.
2. 컴포넌트를 다 만들고 난 다음에 기존에 아이콘 사용한 코드들도 1. 방식으로 리팩토링

이렇게 하면 어떨까하는데 혹시 의견 있으시면 코멘트 남겨주세요.

**Comment by LeagueLugas** [comment]
컴포넌트 작업 다 끝나고 적용하면 좋을거 같아요.
안그래도 지금 방식이 깔끔하지 않았다고 생각한 참이었거든요 ㅎ
